name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your branch
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          check-latest: true

      - name: Install dependencies
        run: npm install

      - name: Install artifacts
        run: npm run update-geo && npx playwright install --with-deps

      - name: Test
        env:
          HOME: /root
        run: npm run ci

      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14

      - name: Build
        run: npm run build-only

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
